version: "3.3"
services:
#  rep-counter-bot:
#    container_name: rep-counter-bot
#    image: rep-counter-bot
#    ports:
#      - "8080:8080"
#    environment:
#      DATASOURCE_URI: ""
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 300M
#    networks:
#      - repcounterbot

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: order-service
      POSTGRES_PASSWORD: order
    volumes:
      - repcounterbot-db:/var/lib/postgresql/data
    networks:
      - repcounterbot

networks:
  repcounterbot:
    driver: bridge

volumes:
  repcounterbot-db:
