version: "3.3"
services:
  repcounterbot:
    container_name: repcounterbot
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: ""
      DATASOURCE_USER: ""
      DATASOURCE_PASSWORD: ""
      BOT_TOKEN: ""
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - local

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: repcounterbot
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    volumes:
      - repcounterbot-db:/var/lib/postgresql/data
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  repcounterbot-db:
