version: "3.3"
services:
  tomcat:
    container_name: tomcat
    image: tomcat
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URI: "mongo"
    volumes:
      - ./logs/:/usr/local/tomcat/logs/
      - ./target/RepCounterBot.war:/usr/local/tomcat/webapps-javaee/ROOT.war
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - repcounterbot

  mongo:
    container_name: mongo
    image: apcheamitru/arm32v7-mongo
    environment:
      MONGO_INITDB_DATABASE: rep-counter-bot
    restart: always
    volumes:
      - ./dbdata:/data/db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - repcounterbot


networks:
  repcounterbot:
    driver: bridge