version: "3.3"
services:
  rep-counter-bot:
    container_name: rep-counter-bot
    image: rep-counter-bot
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URI: "mongodb+srv://repcounterbot-app:rgEthTOPub2oDoJG@repcounterbotcluster.at0fumi.mongodb.net/?retryWrites=true&w=majority&appName=RepCounterBotCluster"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - repcounterbot

networks:
  repcounterbot:
    driver: bridge
